#!/usr/bin/env python3
"""
debug_auth.py – Diagnose 401 "Invalid L1 Request headers" errors.

Tests clock skew, header combinations, and prints everything for debugging.
"""

import os
import sys
import time
import json
import requests
from datetime import datetime
from dotenv import load_dotenv

load_dotenv()

try:
    from py_clob_client.signer import Signer
    from py_clob_client.headers.headers import create_level_1_headers
    from py_clob_client.signing.eip712 import sign_clob_auth_message
    from py_clob_client.constants import POLYGON
except ImportError as e:
    print(f"SDK import error: {e}")
    sys.exit(1)

pk = os.getenv("PRIVATE_KEY", "").strip()
proxy = os.getenv("PROXY_WALLET", "").strip()
host = os.getenv("CLOB_HOST", "https://clob.polymarket.com")

if not pk:
    print("ERROR: PRIVATE_KEY not set in .env")
    sys.exit(1)

if not pk.startswith("0x"):
    pk = "0x" + pk
if proxy and not proxy.startswith("0x"):
    proxy = "0x" + proxy

signer = Signer(pk, POLYGON)
eoa = signer.address()

print("=" * 60)
print("DEBUG AUTH DIAGNOSTICS")
print("=" * 60)
print(f"EOA address (from key): {eoa}")
print(f"Proxy wallet:           {proxy or '(not set)'}")
print(f"CLOB host:              {host}")
print(f"Chain ID:               {POLYGON}")
print(f"Private key:            {pk[:6]}...{pk[-4:]}")
print(f"Key length:             {len(pk)} chars")


# ---- 1. Clock skew check ----
print("\n--- CLOCK SKEW CHECK ---")
local_time = int(time.time())
print(f"Local timestamp:  {local_time}")
print(f"Local datetime:   {datetime.now().isoformat()}")

try:
    # Hit a lightweight endpoint to get server time from response headers
    r = requests.get(f"{host}/time", timeout=5)
    server_time = r.json().get("timestamp") if r.status_code == 200 else None
    if server_time:
        skew = abs(local_time - int(server_time))
        print(f"Server timestamp: {server_time}")
        print(f"Clock skew:       {skew} seconds")
        if skew > 5:
            print("⚠️  SIGNIFICANT CLOCK SKEW DETECTED — this could cause 401 errors!")
    else:
        print(f"Server /time returned: {r.status_code} {r.text[:200]}")
except Exception as e:
    print(f"Could not check server time: {e}")

# Also check via Date header from any endpoint
try:
    r = requests.get(f"{host}/", timeout=5)
    server_date = r.headers.get("Date", "")
    print(f"Server Date header: {server_date}")
except Exception as e:
    print(f"Could not get server Date header: {e}")


# ---- 2. Test SDK-generated headers directly ----
print("\n--- SDK HEADER TEST (EOA address, SDK's create_level_1_headers) ---")
sdk_headers = create_level_1_headers(signer, nonce=0)
print("Headers generated by SDK:")
for k, v in sdk_headers.items():
    display_v = v if len(str(v)) < 40 else f"{v[:20]}...{v[-10:]}"
    print(f"  {k}: {display_v}")


# ---- 3. Try all endpoint + address combos ----
def try_auth(label, method, url, poly_address, nonce=0):
    """Try an auth request with given address in POLY_ADDRESS header."""
    ts = int(time.time())
    sig = sign_clob_auth_message(signer, ts, nonce)

    headers = {
        "POLY_ADDRESS": poly_address,
        "POLY_SIGNATURE": sig,
        "POLY_TIMESTAMP": str(ts),
        "POLY_NONCE": str(nonce),
        "User-Agent": "py_clob_client",
        "Accept": "*/*",
        "Connection": "keep-alive",
        "Content-Type": "application/json",
        "Accept-Encoding": "gzip",
    }

    print(f"\n[{label}]")
    print(f"  {method} {url}")
    print(f"  POLY_ADDRESS: {poly_address}")
    print(f"  POLY_TIMESTAMP: {ts}")

    try:
        if method == "POST":
            resp = requests.post(url, headers=headers, timeout=10)
        else:
            resp = requests.get(url, headers=headers, timeout=10)

        print(f"  Status: {resp.status_code}")
        body = resp.text[:300]
        print(f"  Response: {body}")

        if resp.status_code == 200:
            print("  ✅ SUCCESS!")
            return resp.json()
    except Exception as e:
        print(f"  Error: {e}")

    return None


print("\n--- TESTING AUTH ENDPOINTS ---")

# Test 1: SDK-style (EOA address, POST create)
result = try_auth(
    "Test 1: POST /auth/api-key with EOA",
    "POST", f"{host}/auth/api-key", eoa
)

# Test 2: SDK-style (EOA address, GET derive)
if not result:
    result = try_auth(
        "Test 2: GET /auth/derive-api-key with EOA",
        "GET", f"{host}/auth/derive-api-key", eoa
    )

# Test 3: Proxy address (POST create) — non-standard but worth testing
if not result and proxy:
    result = try_auth(
        "Test 3: POST /auth/api-key with PROXY",
        "POST", f"{host}/auth/api-key", proxy
    )

# Test 4: Proxy address (GET derive) — non-standard but worth testing
if not result and proxy:
    result = try_auth(
        "Test 4: GET /auth/derive-api-key with PROXY",
        "GET", f"{host}/auth/derive-api-key", proxy
    )

# Test 5: Try with nonce=1 (in case nonce=0 is exhausted)
if not result:
    result = try_auth(
        "Test 5: POST /auth/api-key with EOA, nonce=1",
        "POST", f"{host}/auth/api-key", eoa, nonce=1
    )

if result:
    print("\n" + "=" * 60)
    print("✅ SUCCESS! Add these to your .env file:")
    print("=" * 60)
    print(f"POLYMARKET_API_KEY={result.get('apiKey')}")
    print(f"POLYMARKET_API_SECRET={result.get('secret')}")
    print(f"POLYMARKET_API_PASSPHRASE={result.get('passphrase')}")
else:
    print("\n" + "=" * 60)
    print("❌ ALL ATTEMPTS FAILED")
    print("=" * 60)
    print("\nPossible causes:")
    print("  1. Clock skew — check timestamps above. Sync with: sudo ntpdate pool.ntp.org")
    print("  2. Wrong private key — this key may not be registered with Polymarket's CLOB")
    print("  3. Account not CLOB-enabled — you may need to accept CLOB terms on polymarket.com")
    print("  4. Email accounts use a different auth flow — contact Polymarket support")
    print(f"\n  Your EOA from this key: {eoa}")
    print(f"  Your proxy wallet:      {proxy or '(not set)'}")
    print(f"\n  Verify your proxy wallet is correct at: https://polymarket.com (profile/settings)")
